import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "polymarket-market-hygiene-scan",
  name: "Polymarket Market Hygiene Scan",
  description:
    "Fetch active Polymarket markets, deduplicate event variants, flag thin books, and persist hygiene snapshot state.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "limit", type: "number", required: false, default: 500 },
    { name: "dedupMode", type: "string", required: false, default: "slug-plus-question" },
    { name: "thinBookRatio", type: "number", required: false, default: 20 },
    { name: "snapshotPrefix", type: "string", required: false, default: "scanner:" },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "fetch_and_register",
      name: "Fetch markets and register SQL table",
      type: "ts",
      timeout: 45000,
      allow: ["fetchPolymarketData"],
      code: [
        'const limit = 500',
        'const raw = await callTool("fetchPolymarketData", { limit })',
        'const rows = Array.isArray(raw) ? raw : []',
        "",
        'await fs.promises.writeFile(',
        '  "/workspace/scratch/polymarket_raw.json",',
        '  JSON.stringify(rows, null, 2)',
        ')',
        "",
        'await exec("sql query \'DROP TABLE IF EXISTS polymarket_raw\'")',
        'await exec("sql register polymarket_raw /workspace/scratch/polymarket_raw.json --replace")',
        "",
        'export default { fetched: rows.length, table: "polymarket_raw" }',
      ].join("\n"),
    },
    {
      id: "dedup_and_flag",
      name: "Deduplicate events and flag thin books",
      type: "ts",
      depends_on: ["fetch_and_register"],
      timeout: 45000,
      code: [
        "function eventKey(slug) {",
        "  return String(slug || \"\")",
        "    .replace(/-\\\\d{3,}(-\\\\d{3,})+$/, \"\")",
        "    .replace(/-\\\\d+-\\\\d+$/, \"\")",
        "    .replace(/-\\\\d+plus$/, \"\")",
        "    .replace(/-game\\\\d+$/, \"\")",
        "    .replace(/-\\\\d{4}-\\\\d{2}-\\\\d{2}$/, \"\")",
        "}",
        "",
        "function normQ(q) {",
        "  return String(q || \"\")",
        "    .toLowerCase()",
        "    .replace(/game\\\\s*\\\\d+/gi, \"\")",
        "    .replace(/\\\\b(map|round|set)\\\\s*\\\\d+/gi, \"\")",
        "    .replace(/\\\\d{1,2}\\\\/\\\\d{1,2}\\\\/\\\\d{2,4}/g, \"\")",
        "    .replace(/\\\\s+/g, \" \")",
        "    .trim()",
        "}",
        "",
        'const rows = await sql("SELECT slug, question, volume_24h_usd, liquidity_usd, hours_until_end FROM polymarket_raw WHERE CAST(hours_until_end AS REAL) > 0")',
        "const seenSlug = new Set()",
        "const seenQuestion = new Set()",
        "const deduped = []",
        "const thinBooks = []",
        "",
        "for (const row of rows) {",
        "  const slugKey = eventKey(row.slug)",
        "  const questionKey = normQ(row.question)",
        "  if (seenSlug.has(slugKey) || seenQuestion.has(questionKey)) continue",
        "  seenSlug.add(slugKey)",
        "  seenQuestion.add(questionKey)",
        "  const volume = Number(row.volume_24h_usd || 0)",
        "  const liquidity = Math.max(Number(row.liquidity_usd || 0), 1)",
        "  const ratio = volume / liquidity",
        "  const enriched = { ...row, vol_liq_ratio: Number(ratio.toFixed(1)) }",
        "  deduped.push(enriched)",
        "  if (ratio > 20) thinBooks.push(enriched)",
        "}",
        "",
        "const now = new Date().toISOString()",
        'const runKey = "scanner:" + now.slice(0, 13)',
        "const snapshot = { timestamp: now, slugs: deduped.map((r) => r.slug), count: deduped.length }",
        'await kv.set(runKey, JSON.stringify(snapshot))',
        'await kv.set("scanner:latest", JSON.stringify(snapshot))',
        "const entries = await kv.list(\"scanner:\")",
        "const previous = entries",
        "  .filter((e) => e.key !== runKey && e.key !== \"scanner:latest\" && e.key.startsWith(\"scanner:2\"))",
        "  .sort((a, b) => b.key.localeCompare(a.key))",
        "let newCount = deduped.length",
        "let droppedCount = 0",
        "if (previous.length > 0) {",
        '  const prev = JSON.parse(previous[0].value || "{}")',
        "  const prevSet = new Set(Array.isArray(prev.slugs) ? prev.slugs : [])",
        "  newCount = deduped.filter((r) => !prevSet.has(r.slug)).length",
        "  droppedCount = Array.from(prevSet).filter((slug) => !snapshot.slugs.includes(slug)).length",
        "}",
        "const result = { dedupedCount: deduped.length, thinBookCount: thinBooks.length, newCount, droppedCount, thinBooks: thinBooks.slice(0, 50) }",
        'await fs.promises.writeFile("/workspace/scratch/polymarket_scan_result.json", JSON.stringify(result, null, 2))',
        "export default result",
      ].join("\n"),
    },
    {
      id: "persist_artifacts",
      name: "Write human-readable summary",
      type: "ts",
      depends_on: ["dedup_and_flag"],
      timeout: 15000,
      code: [
        'const raw = await fs.promises.readFile("/workspace/scratch/polymarket_scan_result.json", "utf8").catch(() => null)',
        "let output",
        "if (!raw) {",
        '  output = { wroteSummary: false, reason: "missing-scan-result" }',
        "} else {",
        "  const result = JSON.parse(raw)",
        "  const lines = [",
        '    "# Polymarket Scan Summary",',
        '    "",',
        '    "- Deduplicated markets: " + String(result.dedupedCount || 0),',
        '    "- Thin books (>20x vol/liq): " + String(result.thinBookCount || 0),',
        '    "- Newly observed slugs: " + String(result.newCount || 0),',
        '    "- Dropped slugs since previous snapshot: " + String(result.droppedCount || 0),',
        "  ]",
        '  await fs.promises.writeFile("/workspace/scratch/final.md", lines.join("\n"))',
        '  output = { wroteSummary: true }',
        "}",
        "export default output",
      ].join("\n"),
    },
  ],
})
