import defineWorkflow from "/runtime/tools/workflow/defineWorkflow"

export default defineWorkflow({
  version: 1,
  id: "polymarket-signal-scanner",
  name: "Polymarket Signal Scanner",
  description:
    "Scan active Polymarket markets, rank high-signal candidates, and emit submission-ready artifacts.",
  triggers: [{ manual: true }],
  inputs: [
    { name: "limit", type: "number", required: false, default: 400 },
    { name: "minHoursUntilEnd", type: "number", required: false, default: 2 },
    { name: "maxHoursUntilEnd", type: "number", required: false, default: 120 },
    { name: "minLiquidityUsd", type: "number", required: false, default: 5000 },
    { name: "shortlistSize", type: "number", required: false, default: 25 },
    { name: "snapshotPrefix", type: "string", required: false, default: "polymarket-signal-scanner:" },
  ],
  output_mode: "inline",
  steps: [
    {
      id: "fetch_markets",
      name: "Fetch markets and register scan table",
      type: "ts",
      timeout: 45000,
      allow: ["fetchPolymarketData"],
      code: [
        'const limit = Number("{{inputs.limit}}") || 400',
        'const raw = await callTool("fetchPolymarketData", { limit })',
        "const rows = Array.isArray(raw) ? raw : []",
        "",
        'await fs.promises.writeFile("/workspace/scratch/polymarket_signal_scanner_raw.json", JSON.stringify(rows, null, 2))',
        'await exec("sql query \'DROP TABLE IF EXISTS polymarket_signal_scan_raw\'")',
        'await exec("sql register polymarket_signal_scan_raw /workspace/scratch/polymarket_signal_scanner_raw.json --replace")',
        "",
        'export default { fetched: rows.length, table: "polymarket_signal_scan_raw" }',
      ].join("\n"),
    },
    {
      id: "rank_candidates",
      name: "Rank candidates and snapshot shortlist",
      type: "ts",
      depends_on: ["fetch_markets"],
      timeout: 45000,
      code: [
        'const minHours = Number("{{inputs.minHoursUntilEnd}}") || 2',
        'const maxHours = Number("{{inputs.maxHoursUntilEnd}}") || 120',
        'const minLiquidity = Number("{{inputs.minLiquidityUsd}}") || 5000',
        'const shortlistSize = Number("{{inputs.shortlistSize}}") || 25',
        'const prefixInput = "{{inputs.snapshotPrefix}}"',
        'const snapshotPrefix = prefixInput && prefixInput !== "{{inputs.snapshotPrefix}}" ? prefixInput : "polymarket-signal-scanner:"',
        "",
        "function clamp(value, lo, hi) {",
        "  return Math.max(lo, Math.min(hi, value))",
        "}",
        "",
        "function safeNumber(value) {",
        "  const n = Number(value)",
        "  return Number.isFinite(n) ? n : 0",
        "}",
        "",
        "const query = [",
        '  "SELECT slug, question, volume_24h_usd, liquidity_usd, hours_until_end",',
        '  "FROM polymarket_signal_scan_raw",',
        '  "WHERE CAST(hours_until_end AS REAL) >= " + String(minHours),',
        '  "AND CAST(hours_until_end AS REAL) <= " + String(maxHours),',
        '  "AND CAST(liquidity_usd AS REAL) >= " + String(minLiquidity),',
        '].join(" ")',
        "const rows = await sql(query)",
        "",
        "const scored = []",
        "for (const row of rows) {",
        "  const volume24h = safeNumber(row.volume_24h_usd)",
        "  const liquidity = Math.max(safeNumber(row.liquidity_usd), 1)",
        "  const hoursUntilEnd = safeNumber(row.hours_until_end)",
        "  const volLiqRatio = volume24h / liquidity",
        "  const urgency = clamp((maxHours - hoursUntilEnd) / Math.max(maxHours - minHours, 1), 0, 1)",
        "  const activity = clamp(Math.log10(Math.max(volume24h, 1)) / 6, 0, 1)",
        "  const thinness = clamp(volLiqRatio / 25, 0, 1)",
        "  const score = Number((urgency * 35 + activity * 25 + thinness * 40).toFixed(2))",
        "  scored.push({",
        "    slug: row.slug || null,",
        "    question: row.question || null,",
        "    hours_until_end: Number(hoursUntilEnd.toFixed(2)),",
        "    volume_24h_usd: Number(volume24h.toFixed(2)),",
        "    liquidity_usd: Number(liquidity.toFixed(2)),",
        "    vol_liq_ratio: Number(volLiqRatio.toFixed(3)),",
        "    score,",
        "  })",
        "}",
        "",
        "scored.sort((a, b) => b.score - a.score)",
        "const shortlist = scored.slice(0, shortlistSize)",
        "const now = new Date().toISOString()",
        "const runKey = snapshotPrefix + now.slice(0, 13)",
        "const snapshot = { timestamp: now, slugs: shortlist.map((r) => r.slug).filter(Boolean), count: shortlist.length }",
        "await kv.set(runKey, JSON.stringify(snapshot))",
        'await kv.set(snapshotPrefix + "latest", JSON.stringify(snapshot))',
        "const entries = await kv.list(snapshotPrefix)",
        "const previous = entries",
        '  .filter((entry) => entry.key !== runKey && entry.key !== snapshotPrefix + "latest")',
        "  .sort((a, b) => b.key.localeCompare(a.key))",
        "",
        "let newCount = shortlist.length",
        "let droppedCount = 0",
        "if (previous.length > 0) {",
        "  let prev = {}",
        "  try {",
        '    prev = JSON.parse(previous[0].value || "{}")',
        "  } catch (_err) {",
        "    prev = {}",
        "  }",
        "  const prevSlugs = new Set(Array.isArray(prev.slugs) ? prev.slugs : [])",
        "  newCount = shortlist.filter((row) => !prevSlugs.has(row.slug)).length",
        "  droppedCount = Array.from(prevSlugs).filter((slug) => !snapshot.slugs.includes(slug)).length",
        "}",
        "",
        "const result = {",
        "  scannedCount: rows.length,",
        "  shortlistedCount: shortlist.length,",
        "  newCount,",
        "  droppedCount,",
        "  shortlist,",
        "  snapshotKey: runKey,",
        "  snapshotPrefix,",
        "}",
        'await fs.promises.writeFile("/workspace/scratch/polymarket_signal_scanner_result.json", JSON.stringify(result, null, 2))',
        "export default result",
      ].join("\n"),
    },
    {
      id: "emit_submission_artifacts",
      name: "Write submission package and summary",
      type: "ts",
      depends_on: ["rank_candidates"],
      timeout: 20000,
      code: [
        'const raw = await fs.promises.readFile("/workspace/scratch/polymarket_signal_scanner_result.json", "utf8").catch(() => null)',
        "let result = null",
        "if (raw) {",
        "  try {",
        "    result = JSON.parse(raw)",
        "  } catch (_err) {",
        "    result = null",
        "  }",
        "}",
        "if (!result) {",
        "  result = { scannedCount: 0, shortlistedCount: 0, newCount: 0, droppedCount: 0, snapshotKey: null, shortlist: [] }",
        "}",
        "",
        "const submission = {",
        '  id: "polymarket-signal-scanner",',
        '  name: "Polymarket Signal Scanner Workflow",',
        '  type: "workflow",',
        '  category: "workflows/market-data",',
        '  summary: "Scan active Polymarket markets and rank high-signal candidates for downstream review.",',
        '  trigger: "Manual run (schedule-ready for recurring scans).",',
        "  inputs: [",
        '    "limit",',
        '    "minHoursUntilEnd",',
        '    "maxHoursUntilEnd",',
        '    "minLiquidityUsd",',
        '    "shortlistSize",',
        '    "snapshotPrefix",',
        "  ],",
        "  outputs: [",
        '    "ranked shortlist with score, liquidity, and urgency metrics",',
        '    "run-over-run new/dropped candidate counts",',
        '    "submission-ready JSON and markdown summary artifacts",',
        "  ],",
        "  sideEffects: [",
        '    "reads market data via fetchPolymarketData",',
        '    "writes /workspace/scratch/polymarket_signal_scanner_*.json artifacts",',
        '    "persists shortlist snapshots under KV prefix",',
        "  ],",
        "  failureModes: [",
        '    "market data tool timeout or schema drift",',
        '    "numeric cast edge cases from malformed fields",',
        '    "stale or missing prior KV snapshots for diffing",',
        "  ],",
        "  evidence: {",
        '    setup: "workflow validate polymarket-signal-scanner && workflow run polymarket-signal-scanner",',
        '    example: "/workspace/scratch/polymarket_signal_scanner_result.json",',
        "  },",
        "}",
        "",
        'await fs.promises.writeFile("/workspace/scratch/polymarket_signal_scanner_submission.json", JSON.stringify(submission, null, 2))',
        "",
        "const top = Array.isArray(result.shortlist) ? result.shortlist.slice(0, 10) : []",
        "const lines = [",
        '  "# Polymarket Signal Scanner Submission Summary",',
        '  "",',
        '  "- Scanned markets: " + String(result.scannedCount || 0),',
        '  "- Shortlisted: " + String(result.shortlistedCount || 0),',
        '  "- Newly observed: " + String(result.newCount || 0),',
        '  "- Dropped since previous snapshot: " + String(result.droppedCount || 0),',
        '  "- Snapshot key: " + String(result.snapshotKey || "n/a"),',
        '  "",',
        '  "## Top Candidates",',
        "]",
        "for (const row of top) {",
        '  lines.push("- " + String(row.slug || "unknown") + " | score=" + String(row.score || 0) + " | ratio=" + String(row.vol_liq_ratio || 0))',
        "}",
        'await fs.promises.writeFile("/workspace/scratch/final.md", lines.join("\n"))',
        "",
        'export default { wrote: true, submissionPath: "/workspace/scratch/polymarket_signal_scanner_submission.json", summaryPath: "/workspace/scratch/final.md" }',
      ].join("\n"),
    },
  ],
})
